var menudata={children:[
{text:"Hauptseite",url:"index.html"},
{text:"Dateien",url:"files.html",children:[
{text:"Auflistung der Dateien",url:"files.html"},
{text:"Datei-Elemente",url:"globals.html",children:[
{text:"Alle",url:"globals.html",children:[
{text:"a",url:"globals.html#index_a"},
{text:"d",url:"globals.html#index_d"},
{text:"e",url:"globals.html#index_e"},
{text:"h",url:"globals.html#index_h"},
{text:"l",url:"globals.html#index_l"},
{text:"m",url:"globals.html#index_m"},
{text:"p",url:"globals.html#index_p"},
{text:"r",url:"globals.html#index_r"},
{text:"s",url:"globals.html#index_s"},
{text:"t",url:"globals.html#index_t"},
{text:"u",url:"globals.html#index_u"},
{text:"v",url:"globals.html#index_v"},
{text:"z",url:"globals.html#index_z"}]},
{text:"Funktionen",url:"globals_func.html"},
{text:"Variablen",url:"globals_vars.html",children:[
{text:"a",url:"globals_vars.html#index_a"},
{text:"d",url:"globals_vars.html#index_d"},
{text:"h",url:"globals_vars.html#index_h"},
{text:"l",url:"globals_vars.html#index_l"},
{text:"t",url:"globals_vars.html#index_t"},
{text:"v",url:"globals_vars.html#index_v"},
{text:"z",url:"globals_vars.html#index_z"}]},
{text:"Makrodefinitionen",url:"globals_defs.html"}]}]}]}
